package Exception_Coding_Assessment;

public class Challenge4_Exception_Propogation {
    //Show how an exception propagates through method calls.
    //InputChain of method calls with division by zero
    //Output=Exception caught in main method
}
